export const ActionTypes = {
  FETCH_PRODUCT_REQUESTED: 'FETCH_PRODUCT_REQUESTED',
  FETCH_PRODUCT_SUCESS: 'FETCH_PRODUCT_SUCESS',
  FETCH_PRODUCTS: 'FETCH_PRODUCTS',
  SET_PRODUCTS: 'SET_PRODUCTS',
  SELECTED_PRODUCT: 'SELECTED_PRODUCT',
  REMOVE_SELECTED_PRODUCT: 'REMOVE_SELECTED_PRODUCT',
};
